function show_color_coding()

lnames = {
    'Left Ankle',...
    'Left Knee',...
    'Left Hip',...
    'Right Hip',...
    'Right Knee',...
    'Right Ankle',...
    'Left Hand',...
    'Left Elbow',...
    'Left Shoulder',...
    'Right Shoulder',...
    'Right Elbow',...
    'Right Hand',...
    'Lower head',...
    'Upper head',...
    };

colors = joint_colors(14);

figure(1);
clf
set(1, 'Position', [0 0 512 512]);

for i=1:14    
    rectangle('Position',[0,i*60,100,50],'FaceColor',colors(i,:));
    text(120, i*60+25, lnames{i});
end
axis equal
axis off

export_fig('../result/color_coding.pdf','-transparent');
